import { contextBridge, ipcRenderer } from "electron";
import type {
  BrowserInfo,
  BattlefieldOption,
  CommunityMatch,
  CaptureDiagnosticsSummary,
  CaptureEvent,
  CaptureHealth,
  DeckNotebook,
  DeckTrackerState,
  GamePlatform,
  HubActionResult,
  ImportSummary,
  MatchDraft,
  OverlayInfo,
  PrivateHubSyncResult,
  ReplayVideoAsset,
  ReplayVideoFinalizeOptions,
  ReplayVideoKeyframeOptions,
  ReplayWindowCaptureSource,
  ReplayVideoSession,
  ReplayVideoStartOptions,
  ReplayRecord,
  ReplayScreenshotFrame,
  ReplayVideoCaptureMode,
  RiftLiteApi,
  SavedDeck,
  ScreenshotResult,
  UpdateStatus,
  UserSettings
} from "../shared/types.js";

const api: RiftLiteApi = {
  getSettings: () => ipcRenderer.invoke("settings:get") as Promise<UserSettings>,
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings) as Promise<UserSettings>,
  getCaptureHealth: () => ipcRenderer.invoke("capture:health:get") as Promise<CaptureHealth>,
  forceCaptureReview: (platform) => ipcRenderer.invoke("capture:force-review", platform) as Promise<MatchDraft | null>,
  getMatches: () => ipcRenderer.invoke("matches:get") as Promise<MatchDraft[]>,
  getDeletedMatches: () => ipcRenderer.invoke("matches:deleted") as Promise<MatchDraft[]>,
  saveMatchDraft: (draft) => ipcRenderer.invoke("matches:save-draft", draft) as Promise<MatchDraft>,
  confirmMatch: (draft) => ipcRenderer.invoke("matches:confirm", draft) as Promise<MatchDraft>,
  previewCombinedMatches: (matchIds) => ipcRenderer.invoke("matches:combine-preview", matchIds) as ReturnType<RiftLiteApi["previewCombinedMatches"]>,
  saveCombinedMatches: (payload) => ipcRenderer.invoke("matches:combine-save", payload) as Promise<MatchDraft>,
  undoCombinedMatch: (combinedMatchId) => ipcRenderer.invoke("matches:combine-undo", combinedMatchId) as Promise<MatchDraft[]>,
  deleteMatch: (id) => ipcRenderer.invoke("matches:delete", id) as Promise<void>,
  restoreMatch: (id) => ipcRenderer.invoke("matches:restore", id) as Promise<MatchDraft | null>,
  purgeMatch: (id) => ipcRenderer.invoke("matches:purge", id) as Promise<void>,
  exportMatchHistoryCsv: (payload) => ipcRenderer.invoke("matches:export-csv", payload) as ReturnType<RiftLiteApi["exportMatchHistoryCsv"]>,
  getDecks: () => ipcRenderer.invoke("decks:get") as Promise<SavedDeck[]>,
  importDeck: (url) => ipcRenderer.invoke("decks:import", url) as Promise<SavedDeck>,
  importDeckText: (text) => ipcRenderer.invoke("decks:import-text", text) as Promise<SavedDeck>,
  refreshDeck: (id) => ipcRenderer.invoke("decks:refresh", id) as Promise<SavedDeck>,
  renameDeck: (id, title) => ipcRenderer.invoke("decks:rename", id, title) as Promise<SavedDeck>,
  deleteDeck: (id) => ipcRenderer.invoke("decks:delete", id) as Promise<void>,
  setActiveDeck: (id) => ipcRenderer.invoke("decks:set-active", id) as Promise<UserSettings>,
  getDeckNotebook: (deckId) => ipcRenderer.invoke("decks:notebook:get", deckId) as Promise<DeckNotebook>,
  saveDeckNotebook: (deckId, notebook) => ipcRenderer.invoke("decks:notebook:save", deckId, notebook) as Promise<DeckNotebook>,
  exportDeckNotebook: (deckId) => ipcRenderer.invoke("decks:notebook:export", deckId) as Promise<string>,
  importDeckNotebook: () => ipcRenderer.invoke("decks:notebook:import") as Promise<DeckNotebook | null>,
  exportDeckPackage: (deckId, notebook) => ipcRenderer.invoke("decks:package:export", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPackage"]>,
  importDeckPackage: () => ipcRenderer.invoke("decks:package:import") as ReturnType<RiftLiteApi["importDeckPackage"]>,
  exportDeckPackageText: (deckId, notebook) => ipcRenderer.invoke("decks:package:export-text", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPackageText"]>,
  importDeckPackageText: (text) => ipcRenderer.invoke("decks:package:import-text", text) as ReturnType<RiftLiteApi["importDeckPackageText"]>,
  exportDeckPrepPdf: (deckId, notebook) => ipcRenderer.invoke("decks:prep:export-pdf", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPrepPdf"]>,
  writeClipboardText: (text) => ipcRenderer.invoke("clipboard:write-text", text) as ReturnType<RiftLiteApi["writeClipboardText"]>,
  getActiveDeckPrep: (opponentLegend) => ipcRenderer.invoke("decks:prep:get-active", opponentLegend) as ReturnType<RiftLiteApi["getActiveDeckPrep"]>,
  getDeckTrackerState: () => ipcRenderer.invoke("deck-tracker:get-state") as Promise<DeckTrackerState>,
  setDeckTrackerPinnedCards: (deckId, cardKeys) => ipcRenderer.invoke("deck-tracker:set-pinned", deckId, cardKeys) as Promise<DeckTrackerState>,
  adjustDeckTrackerCard: (cardKey, delta) => ipcRenderer.invoke("deck-tracker:adjust", cardKey, delta) as Promise<DeckTrackerState>,
  adjustDeckTrackerSideboard: (cardKey, direction, delta) => ipcRenderer.invoke("deck-tracker:sideboard-adjust", cardKey, direction, delta) as Promise<DeckTrackerState>,
  resetDeckTrackerSideboard: () => ipcRenderer.invoke("deck-tracker:sideboard-reset") as Promise<DeckTrackerState>,
  resetDeckTrackerMatch: () => ipcRenderer.invoke("deck-tracker:reset") as Promise<DeckTrackerState>,
  openDeckTrackerWindow: () => ipcRenderer.invoke("deck-tracker:open-window") as Promise<void>,
  getVisionDeckTrackerStatus: () => ipcRenderer.invoke("vision-deck-tracker:get-status") as ReturnType<RiftLiteApi["getVisionDeckTrackerStatus"]>,
  setVisionDeckTrackerEnabled: (enabled) => ipcRenderer.invoke("vision-deck-tracker:set-enabled", enabled) as Promise<UserSettings>,
  calibrateVisionDeckTracker: (platform) => ipcRenderer.invoke("vision-deck-tracker:calibrate", platform) as ReturnType<RiftLiteApi["calibrateVisionDeckTracker"]>,
  confirmVisionDeckTrackerSuggestion: (cardKey) => ipcRenderer.invoke("vision-deck-tracker:confirm-suggestion", cardKey) as ReturnType<RiftLiteApi["confirmVisionDeckTrackerSuggestion"]>,
  rejectVisionDeckTrackerSuggestion: (cardKey) => ipcRenderer.invoke("vision-deck-tracker:reject-suggestion", cardKey) as ReturnType<RiftLiteApi["rejectVisionDeckTrackerSuggestion"]>,
  reportVisionDeckTrackerObservations: (platform, observations, status) => ipcRenderer.invoke("vision-deck-tracker:observations", platform, observations, status) as Promise<DeckTrackerState>,
  recordVisionDeckTrackerDebug: (platform, payload) => ipcRenderer.invoke("vision-deck-tracker:debug", platform, payload) as Promise<void>,
  getReplays: () => ipcRenderer.invoke("replays:get") as Promise<ReplayRecord[]>,
  getDeletedReplays: () => ipcRenderer.invoke("replays:deleted") as Promise<ReplayRecord[]>,
  saveReplay: (replay) => ipcRenderer.invoke("replays:save", replay) as Promise<ReplayRecord>,
  deleteReplay: (id) => ipcRenderer.invoke("replays:delete", id) as Promise<void>,
  restoreReplay: (id) => ipcRenderer.invoke("replays:restore", id) as Promise<ReplayRecord | null>,
  purgeReplay: (id) => ipcRenderer.invoke("replays:purge", id) as Promise<void>,
  exportReplayBundle: (replayId) => ipcRenderer.invoke("replays:export", replayId) as Promise<string>,
  exportReplayMp4: (replayId, options) => ipcRenderer.invoke("replays:export-mp4", replayId, options) as ReturnType<RiftLiteApi["exportReplayMp4"]>,
  exportReplayPresentationMp4: (replayId, payload) => ipcRenderer.invoke("replays:export-presentation-mp4", replayId, payload) as ReturnType<RiftLiteApi["exportReplayPresentationMp4"]>,
  exportReplayFlagsText: (replayId) => ipcRenderer.invoke("replays:export-flags-text", replayId) as ReturnType<RiftLiteApi["exportReplayFlagsText"]>,
  uploadRawCapture: (replayId) => ipcRenderer.invoke("raw-capture:upload", replayId) as ReturnType<RiftLiteApi["uploadRawCapture"]>,
  getRawCaptureStatus: () => ipcRenderer.invoke("raw-capture:status") as ReturnType<RiftLiteApi["getRawCaptureStatus"]>,
  getRawCapturePayload: (replayId) => ipcRenderer.invoke("raw-capture:payload", replayId) as ReturnType<RiftLiteApi["getRawCapturePayload"]>,
  uploadRawCaptureToRiftLite: (replayId, visibility) => ipcRenderer.invoke("raw-capture:upload-riftlite", replayId, visibility) as ReturnType<RiftLiteApi["uploadRawCaptureToRiftLite"]>,
  shareRawCaptureToDiscord: (replayId) => ipcRenderer.invoke("raw-capture:share-discord", replayId) as ReturnType<RiftLiteApi["shareRawCaptureToDiscord"]>,
  prepareReplayEmbed: (replayId) => ipcRenderer.invoke("replay:embed:prepare", replayId) as ReturnType<RiftLiteApi["prepareReplayEmbed"]>,
  prepareReplayLibraryEmbed: () => ipcRenderer.invoke("replay:embed:prepare-library") as ReturnType<RiftLiteApi["prepareReplayLibraryEmbed"]>,
  importReplayBundle: () => ipcRenderer.invoke("replays:import") as Promise<ReplayRecord | null>,
  importReplayFolder: () => ipcRenderer.invoke("replays:import-folder") as Promise<ReplayRecord[]>,
  openReplayFolder: () => ipcRenderer.invoke("replays:open-folder") as Promise<void>,
  startReplayVideoCapture: (options: ReplayVideoStartOptions) => ipcRenderer.invoke("replays:video:start", options) as Promise<ReplayVideoSession>,
  prepareReplayVideoCaptureTarget: (platform: GamePlatform, mode: ReplayVideoCaptureMode) => ipcRenderer.invoke("replays:video:prepare-target", platform, mode) as Promise<void>,
  getReplayWindowCaptureSource: () => ipcRenderer.invoke("replays:video:window-source") as Promise<ReplayWindowCaptureSource | null>,
  appendReplayVideoChunk: (sessionId: string, chunk: ArrayBuffer) => ipcRenderer.invoke("replays:video:chunk", sessionId, chunk) as Promise<void>,
  finishReplayVideoCapture: (sessionId: string, options: ReplayVideoFinalizeOptions) => ipcRenderer.invoke("replays:video:finish", sessionId, options) as Promise<ReplayVideoAsset>,
  mergeReplayVideos: (segments, options) => ipcRenderer.invoke("replays:video:merge", segments, options) as ReturnType<RiftLiteApi["mergeReplayVideos"]>,
  attachReplayVideo: (matchId: string, video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:attach", matchId, video) as Promise<ReplayRecord | null>,
  discardReplayVideo: (video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:discard", video) as Promise<void>,
  deleteReplayVideoByMatch: (matchId: string) => ipcRenderer.invoke("replays:video:delete-by-match", matchId) as Promise<void>,
  saveReplayVideoKeyframe: (options: ReplayVideoKeyframeOptions) => ipcRenderer.invoke("replays:video:keyframe", options) as Promise<ReplayScreenshotFrame>,
  loadReplayVideo: (video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:load", video) as Promise<ArrayBuffer>,
  importLegacyData: () => ipcRenderer.invoke("legacy:import") as Promise<ImportSummary>,
  exportBackup: (options) => ipcRenderer.invoke("backup:export", options) as ReturnType<RiftLiteApi["exportBackup"]>,
  restoreBackup: () => ipcRenderer.invoke("backup:restore") as ReturnType<RiftLiteApi["restoreBackup"]>,
  getCommunityMatches: (forceRefresh) => ipcRenderer.invoke("community:matches", forceRefresh) as Promise<CommunityMatch[]>,
  getHubMatches: (hubId, forceRefresh) => ipcRenderer.invoke("hubs:matches", hubId, forceRefresh) as Promise<CommunityMatch[]>,
  createHub: (name, password) => ipcRenderer.invoke("hubs:create", name, password) as Promise<HubActionResult>,
  joinHub: (name, password) => ipcRenderer.invoke("hubs:join", name, password) as Promise<HubActionResult>,
  refreshAccountHubs: () => ipcRenderer.invoke("hubs:refresh-account") as ReturnType<RiftLiteApi["refreshAccountHubs"]>,
  syncPrivateHubs: () => ipcRenderer.invoke("hubs:sync-private") as Promise<PrivateHubSyncResult>,
  syncMatchesToHubs: (matchIds, hubIds) => ipcRenderer.invoke("hubs:sync-selected", matchIds, hubIds) as Promise<PrivateHubSyncResult>,
  deleteHubMatch: (hubId, matchId) => ipcRenderer.invoke("hubs:delete-match", hubId, matchId) as Promise<void>,
  getTeamMatches: (teamId, forceRefresh) => ipcRenderer.invoke("teams:matches", teamId, forceRefresh) as Promise<CommunityMatch[]>,
  syncTeams: () => ipcRenderer.invoke("teams:sync-enabled") as Promise<PrivateHubSyncResult>,
  syncMatchesToTeams: (matchIds, teamIds) => ipcRenderer.invoke("teams:sync-selected", matchIds, teamIds) as Promise<PrivateHubSyncResult>,
  deleteTeamMatch: (teamId, matchId) => ipcRenderer.invoke("teams:delete-match", teamId, matchId) as Promise<void>,
  startAccountLink: () => ipcRenderer.invoke("account:link:start") as ReturnType<RiftLiteApi["startAccountLink"]>,
  getAccountLinkStatus: (sessionId) => ipcRenderer.invoke("account:link:status", sessionId) as ReturnType<RiftLiteApi["getAccountLinkStatus"]>,
  getAccountConnectionStatus: () => ipcRenderer.invoke("account:connection:status") as ReturnType<RiftLiteApi["getAccountConnectionStatus"]>,
  repairAccountConnection: () => ipcRenderer.invoke("account:connection:repair") as ReturnType<RiftLiteApi["repairAccountConnection"]>,
  getAccountProfile: () => ipcRenderer.invoke("account:profile:get") as ReturnType<RiftLiteApi["getAccountProfile"]>,
  saveAccountProfile: (profile) => ipcRenderer.invoke("account:profile:save", profile) as ReturnType<RiftLiteApi["saveAccountProfile"]>,
  refreshAccountProfileMatches: () => ipcRenderer.invoke("account:profile:backfill") as ReturnType<RiftLiteApi["refreshAccountProfileMatches"]>,
  exportAccountData: () => ipcRenderer.invoke("account:export") as ReturnType<RiftLiteApi["exportAccountData"]>,
  getAccountCloudSyncStatus: () => ipcRenderer.invoke("account:cloud-sync:status") as ReturnType<RiftLiteApi["getAccountCloudSyncStatus"]>,
  setAccountCloudSyncEnabled: (enabled) => ipcRenderer.invoke("account:cloud-sync:set-enabled", enabled) as ReturnType<RiftLiteApi["setAccountCloudSyncEnabled"]>,
  uploadAccountCloudSync: () => ipcRenderer.invoke("account:cloud-sync:upload") as ReturnType<RiftLiteApi["uploadAccountCloudSync"]>,
  restoreAccountCloudSync: () => ipcRenderer.invoke("account:cloud-sync:restore") as ReturnType<RiftLiteApi["restoreAccountCloudSync"]>,
  unlinkAccount: () => ipcRenderer.invoke("account:unlink") as ReturnType<RiftLiteApi["unlinkAccount"]>,
  searchPublicProfiles: (query) => ipcRenderer.invoke("profiles:search", query) as ReturnType<RiftLiteApi["searchPublicProfiles"]>,
  claimHub: (hubId, password) => ipcRenderer.invoke("hubs:claim", hubId, password) as ReturnType<RiftLiteApi["claimHub"]>,
  getHubInbox: () => ipcRenderer.invoke("hubs:inbox") as ReturnType<RiftLiteApi["getHubInbox"]>,
  acceptHubInvite: (inviteId) => ipcRenderer.invoke("hubs:invite:accept", inviteId) as ReturnType<RiftLiteApi["acceptHubInvite"]>,
  declineHubInvite: (inviteId) => ipcRenderer.invoke("hubs:invite:decline", inviteId) as ReturnType<RiftLiteApi["declineHubInvite"]>,
  getHubMembers: (hubId) => ipcRenderer.invoke("hubs:members", hubId) as ReturnType<RiftLiteApi["getHubMembers"]>,
  getHubHealth: (hubId) => ipcRenderer.invoke("hubs:health", hubId) as ReturnType<RiftLiteApi["getHubHealth"]>,
  updateHubMemberRole: (hubId, uid, role) => ipcRenderer.invoke("hubs:member:update", hubId, uid, role) as ReturnType<RiftLiteApi["updateHubMemberRole"]>,
  createHubInvite: (hubId, targetHandle) => ipcRenderer.invoke("hubs:invite", hubId, targetHandle) as ReturnType<RiftLiteApi["createHubInvite"]>,
  getHubMessages: (hubId) => ipcRenderer.invoke("hubs:messages", hubId) as ReturnType<RiftLiteApi["getHubMessages"]>,
  postHubMessage: (hubId, text) => ipcRenderer.invoke("hubs:message:post", hubId, text) as ReturnType<RiftLiteApi["postHubMessage"]>,
  deleteHubMessage: (hubId, messageId) => ipcRenderer.invoke("hubs:message:delete", hubId, messageId) as ReturnType<RiftLiteApi["deleteHubMessage"]>,
  getLfgListings: (includeMine) => ipcRenderer.invoke("lfg:list", includeMine) as ReturnType<RiftLiteApi["getLfgListings"]>,
  createLfgListing: (draft) => ipcRenderer.invoke("lfg:create", draft) as ReturnType<RiftLiteApi["createLfgListing"]>,
  acceptLfgListing: (listingId) => ipcRenderer.invoke("lfg:accept", listingId) as ReturnType<RiftLiteApi["acceptLfgListing"]>,
  closeLfgListing: (listingId) => ipcRenderer.invoke("lfg:close", listingId) as ReturnType<RiftLiteApi["closeLfgListing"]>,
  createLfgVoice: (listingId) => ipcRenderer.invoke("lfg:voice:create", listingId) as ReturnType<RiftLiteApi["createLfgVoice"]>,
  joinDiscordVoice: (listing) => ipcRenderer.invoke("discord:voice:join", listing) as ReturnType<RiftLiteApi["joinDiscordVoice"]>,
  getSocialTeams: (options) => ipcRenderer.invoke("teams:list", options) as ReturnType<RiftLiteApi["getSocialTeams"]>,
  createSocialTeam: (draft) => ipcRenderer.invoke("teams:create", draft) as ReturnType<RiftLiteApi["createSocialTeam"]>,
  getSocialTeam: (teamId) => ipcRenderer.invoke("teams:get", teamId) as ReturnType<RiftLiteApi["getSocialTeam"]>,
  updateSocialTeam: (teamId, patch) => ipcRenderer.invoke("teams:update", teamId, patch) as ReturnType<RiftLiteApi["updateSocialTeam"]>,
  applyToSocialTeam: (teamId, draft) => ipcRenderer.invoke("teams:apply", teamId, draft) as ReturnType<RiftLiteApi["applyToSocialTeam"]>,
  getSocialTeamApplications: (teamId) => ipcRenderer.invoke("teams:applications", teamId) as ReturnType<RiftLiteApi["getSocialTeamApplications"]>,
  reviewSocialTeamApplication: (teamId, applicationId, status) => ipcRenderer.invoke("teams:application:review", teamId, applicationId, status) as ReturnType<RiftLiteApi["reviewSocialTeamApplication"]>,
  getSocialTeamMessages: (teamId) => ipcRenderer.invoke("teams:messages", teamId) as ReturnType<RiftLiteApi["getSocialTeamMessages"]>,
  postSocialTeamMessage: (teamId, text) => ipcRenderer.invoke("teams:message:post", teamId, text) as ReturnType<RiftLiteApi["postSocialTeamMessage"]>,
  deleteSocialTeamMessage: (teamId, messageId) => ipcRenderer.invoke("teams:message:delete", teamId, messageId) as ReturnType<RiftLiteApi["deleteSocialTeamMessage"]>,
  updateSocialTeamMember: (teamId, uid, role) => ipcRenderer.invoke("teams:member:update", teamId, uid, role) as ReturnType<RiftLiteApi["updateSocialTeamMember"]>,
  removeSocialTeamMember: (teamId, uid) => ipcRenderer.invoke("teams:member:remove", teamId, uid) as ReturnType<RiftLiteApi["removeSocialTeamMember"]>,
  reportSocialTeam: (payload) => ipcRenderer.invoke("teams:report", payload) as ReturnType<RiftLiteApi["reportSocialTeam"]>,
  getModerationTeams: (query) => ipcRenderer.invoke("moderation:teams", query) as ReturnType<RiftLiteApi["getModerationTeams"]>,
  moderateTeam: (teamId, action, reason) => ipcRenderer.invoke("moderation:team:update", teamId, action, reason) as ReturnType<RiftLiteApi["moderateTeam"]>,
  onAppNavigate: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload);
    ipcRenderer.on("app:navigate", listener);
    return () => ipcRenderer.removeListener("app:navigate", listener);
  },
  getUpdateStatus: () => ipcRenderer.invoke("updates:status") as Promise<UpdateStatus>,
  checkForUpdates: () => ipcRenderer.invoke("updates:check") as Promise<UpdateStatus>,
  downloadUpdate: () => ipcRenderer.invoke("updates:download") as Promise<UpdateStatus>,
  installUpdate: () => ipcRenderer.invoke("updates:install") as Promise<void>,
  recoverAtlasWebview: () => ipcRenderer.invoke("atlas-webview:recover") as ReturnType<RiftLiteApi["recoverAtlasWebview"]>,
  getGamePreloadUrl: (platform: GamePlatform) => ipcRenderer.invoke("game-preload:url", platform) as Promise<string>,
  getAssetUrl: (relativePath: string) => ipcRenderer.invoke("assets:url", relativePath) as Promise<string>,
  getBattlefields: () => ipcRenderer.invoke("battlefields:get") as Promise<BattlefieldOption[]>,
  notifyMatchReady: (draft) => ipcRenderer.invoke("notification:match-ready", draft) as Promise<void>,
  detectBrowsers: () => ipcRenderer.invoke("browsers:detect") as Promise<BrowserInfo[]>,
  getOverlayInfo: () => ipcRenderer.invoke("overlay:info") as Promise<OverlayInfo>,
  openOverlayTextFolder: () => ipcRenderer.invoke("overlay:open-text-folder") as Promise<void>,
  getDiagnosticsPath: () => ipcRenderer.invoke("diagnostics:path") as Promise<string>,
  getDiagnosticsSummary: () => ipcRenderer.invoke("diagnostics:summary") as Promise<CaptureDiagnosticsSummary>,
  createDiagnosticsBundle: () => ipcRenderer.invoke("diagnostics:bundle") as Promise<string>,
  openDiagnosticsFolder: () => ipcRenderer.invoke("diagnostics:open") as Promise<void>,
  takeScreenshot: () => ipcRenderer.invoke("screenshot:take") as Promise<ScreenshotResult>,
  chooseScreenshotDirectory: () => ipcRenderer.invoke("screenshot:choose-directory") as Promise<UserSettings>,
  openScreenshotDirectory: () => ipcRenderer.invoke("screenshot:open-directory") as Promise<void>,
  chooseReplayDirectory: () => ipcRenderer.invoke("replays:choose-directory") as Promise<UserSettings>,
  openReplayDirectory: () => ipcRenderer.invoke("replays:open-directory") as Promise<void>,
  openExternalResource: (url: string) => ipcRenderer.invoke("external:open", url) as Promise<void>,
  setWindowFullscreen: (enabled) => ipcRenderer.invoke("window:fullscreen", enabled) as Promise<boolean>,
  trackSpotlightClick: (payload) => ipcRenderer.invoke("analytics:spotlight-click", payload) as Promise<void>,
  reportRendererEvent: (event) => ipcRenderer.invoke("capture:renderer-event", event) as Promise<void>,
  onCaptureEvent: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: CaptureEvent) => callback(payload);
    ipcRenderer.on("capture:event", listener);
    return () => ipcRenderer.removeListener("capture:event", listener);
  },
  onCaptureHealth: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: CaptureHealth) => callback(payload);
    ipcRenderer.on("capture:health", listener);
    return () => ipcRenderer.removeListener("capture:health", listener);
  },
  onMatchDraft: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: MatchDraft) => callback(payload);
    ipcRenderer.on("match:draft", listener);
    return () => ipcRenderer.removeListener("match:draft", listener);
  },
  onScreenshotSaved: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: ScreenshotResult) => callback(payload);
    ipcRenderer.on("screenshot:saved", listener);
    return () => ipcRenderer.removeListener("screenshot:saved", listener);
  },
  onReplayShadowClipHotkey: (callback) => {
    const listener = () => callback();
    ipcRenderer.on("replay:shadow-clip-hotkey", listener);
    return () => ipcRenderer.removeListener("replay:shadow-clip-hotkey", listener);
  },
  onReplayQuickFlagHotkey: (callback) => {
    const listener = () => callback();
    ipcRenderer.on("replay:quick-flag-hotkey", listener);
    return () => ipcRenderer.removeListener("replay:quick-flag-hotkey", listener);
  },
  onUpdateStatus: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: UpdateStatus) => callback(payload);
    ipcRenderer.on("updates:status", listener);
    return () => ipcRenderer.removeListener("updates:status", listener);
  }
};

contextBridge.exposeInMainWorld("riftlite", api);
