import { contextBridge, ipcRenderer } from "electron";
import type {
  BrowserInfo,
  BattlefieldOption,
  CommunityMatch,
  CaptureDiagnosticsSummary,
  CaptureEvent,
  CaptureHealth,
  DeckNotebook,
  DeckTrackerState,
  GamePlatform,
  HubActionResult,
  ImportSummary,
  MatchDraft,
  OverlayInfo,
  PrivateHubSyncResult,
  ReplayVideoAsset,
  ReplayVideoFinalizeOptions,
  ReplayVideoKeyframeOptions,
  ReplayWindowCaptureSource,
  ReplayVideoSession,
  ReplayVideoStartOptions,
  ReplayRecord,
  ReplayScreenshotFrame,
  ReplayVideoCaptureMode,
  RiftLiteApi,
  SavedDeck,
  ScreenshotResult,
  UpdateStatus,
  UserSettings
} from "../shared/types.js";

const api: RiftLiteApi = {
  getSettings: () => ipcRenderer.invoke("settings:get") as Promise<UserSettings>,
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings) as Promise<UserSettings>,
  getCaptureHealth: () => ipcRenderer.invoke("capture:health:get") as Promise<CaptureHealth>,
  forceCaptureReview: (platform) => ipcRenderer.invoke("capture:force-review", platform) as Promise<MatchDraft | null>,
  getMatches: () => ipcRenderer.invoke("matches:get") as Promise<MatchDraft[]>,
  getDeletedMatches: () => ipcRenderer.invoke("matches:deleted") as Promise<MatchDraft[]>,
  saveMatchDraft: (draft) => ipcRenderer.invoke("matches:save-draft", draft) as Promise<MatchDraft>,
  confirmMatch: (draft) => ipcRenderer.invoke("matches:confirm", draft) as Promise<MatchDraft>,
  deleteMatch: (id) => ipcRenderer.invoke("matches:delete", id) as Promise<void>,
  restoreMatch: (id) => ipcRenderer.invoke("matches:restore", id) as Promise<MatchDraft | null>,
  purgeMatch: (id) => ipcRenderer.invoke("matches:purge", id) as Promise<void>,
  exportMatchHistoryCsv: (payload) => ipcRenderer.invoke("matches:export-csv", payload) as ReturnType<RiftLiteApi["exportMatchHistoryCsv"]>,
  getDecks: () => ipcRenderer.invoke("decks:get") as Promise<SavedDeck[]>,
  importDeck: (url) => ipcRenderer.invoke("decks:import", url) as Promise<SavedDeck>,
  importDeckText: (text) => ipcRenderer.invoke("decks:import-text", text) as Promise<SavedDeck>,
  refreshDeck: (id) => ipcRenderer.invoke("decks:refresh", id) as Promise<SavedDeck>,
  renameDeck: (id, title) => ipcRenderer.invoke("decks:rename", id, title) as Promise<SavedDeck>,
  deleteDeck: (id) => ipcRenderer.invoke("decks:delete", id) as Promise<void>,
  setActiveDeck: (id) => ipcRenderer.invoke("decks:set-active", id) as Promise<UserSettings>,
  getDeckNotebook: (deckId) => ipcRenderer.invoke("decks:notebook:get", deckId) as Promise<DeckNotebook>,
  saveDeckNotebook: (deckId, notebook) => ipcRenderer.invoke("decks:notebook:save", deckId, notebook) as Promise<DeckNotebook>,
  exportDeckNotebook: (deckId) => ipcRenderer.invoke("decks:notebook:export", deckId) as Promise<string>,
  importDeckNotebook: () => ipcRenderer.invoke("decks:notebook:import") as Promise<DeckNotebook | null>,
  exportDeckPackage: (deckId, notebook) => ipcRenderer.invoke("decks:package:export", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPackage"]>,
  importDeckPackage: () => ipcRenderer.invoke("decks:package:import") as ReturnType<RiftLiteApi["importDeckPackage"]>,
  exportDeckPackageText: (deckId, notebook) => ipcRenderer.invoke("decks:package:export-text", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPackageText"]>,
  importDeckPackageText: (text) => ipcRenderer.invoke("decks:package:import-text", text) as ReturnType<RiftLiteApi["importDeckPackageText"]>,
  exportDeckPrepPdf: (deckId, notebook) => ipcRenderer.invoke("decks:prep:export-pdf", deckId, notebook) as ReturnType<RiftLiteApi["exportDeckPrepPdf"]>,
  writeClipboardText: (text) => ipcRenderer.invoke("clipboard:write-text", text) as ReturnType<RiftLiteApi["writeClipboardText"]>,
  getActiveDeckPrep: (opponentLegend) => ipcRenderer.invoke("decks:prep:get-active", opponentLegend) as ReturnType<RiftLiteApi["getActiveDeckPrep"]>,
  getDeckTrackerState: () => ipcRenderer.invoke("deck-tracker:get-state") as Promise<DeckTrackerState>,
  setDeckTrackerPinnedCards: (deckId, cardKeys) => ipcRenderer.invoke("deck-tracker:set-pinned", deckId, cardKeys) as Promise<DeckTrackerState>,
  adjustDeckTrackerCard: (cardKey, delta) => ipcRenderer.invoke("deck-tracker:adjust", cardKey, delta) as Promise<DeckTrackerState>,
  resetDeckTrackerMatch: () => ipcRenderer.invoke("deck-tracker:reset") as Promise<DeckTrackerState>,
  getReplays: () => ipcRenderer.invoke("replays:get") as Promise<ReplayRecord[]>,
  getDeletedReplays: () => ipcRenderer.invoke("replays:deleted") as Promise<ReplayRecord[]>,
  saveReplay: (replay) => ipcRenderer.invoke("replays:save", replay) as Promise<ReplayRecord>,
  deleteReplay: (id) => ipcRenderer.invoke("replays:delete", id) as Promise<void>,
  restoreReplay: (id) => ipcRenderer.invoke("replays:restore", id) as Promise<ReplayRecord | null>,
  purgeReplay: (id) => ipcRenderer.invoke("replays:purge", id) as Promise<void>,
  exportReplayBundle: (replayId) => ipcRenderer.invoke("replays:export", replayId) as Promise<string>,
  exportReplayMp4: (replayId, options) => ipcRenderer.invoke("replays:export-mp4", replayId, options) as ReturnType<RiftLiteApi["exportReplayMp4"]>,
  importReplayBundle: () => ipcRenderer.invoke("replays:import") as Promise<ReplayRecord | null>,
  importReplayFolder: () => ipcRenderer.invoke("replays:import-folder") as Promise<ReplayRecord[]>,
  openReplayFolder: () => ipcRenderer.invoke("replays:open-folder") as Promise<void>,
  startReplayVideoCapture: (options: ReplayVideoStartOptions) => ipcRenderer.invoke("replays:video:start", options) as Promise<ReplayVideoSession>,
  prepareReplayVideoCaptureTarget: (platform: GamePlatform, mode: ReplayVideoCaptureMode) => ipcRenderer.invoke("replays:video:prepare-target", platform, mode) as Promise<void>,
  getReplayWindowCaptureSource: () => ipcRenderer.invoke("replays:video:window-source") as Promise<ReplayWindowCaptureSource | null>,
  appendReplayVideoChunk: (sessionId: string, chunk: ArrayBuffer) => ipcRenderer.invoke("replays:video:chunk", sessionId, chunk) as Promise<void>,
  finishReplayVideoCapture: (sessionId: string, options: ReplayVideoFinalizeOptions) => ipcRenderer.invoke("replays:video:finish", sessionId, options) as Promise<ReplayVideoAsset>,
  mergeReplayVideos: (segments, options) => ipcRenderer.invoke("replays:video:merge", segments, options) as ReturnType<RiftLiteApi["mergeReplayVideos"]>,
  attachReplayVideo: (matchId: string, video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:attach", matchId, video) as Promise<ReplayRecord | null>,
  discardReplayVideo: (video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:discard", video) as Promise<void>,
  deleteReplayVideoByMatch: (matchId: string) => ipcRenderer.invoke("replays:video:delete-by-match", matchId) as Promise<void>,
  saveReplayVideoKeyframe: (options: ReplayVideoKeyframeOptions) => ipcRenderer.invoke("replays:video:keyframe", options) as Promise<ReplayScreenshotFrame>,
  loadReplayVideo: (video: ReplayVideoAsset) => ipcRenderer.invoke("replays:video:load", video) as Promise<ArrayBuffer>,
  importLegacyData: () => ipcRenderer.invoke("legacy:import") as Promise<ImportSummary>,
  getCommunityMatches: (forceRefresh) => ipcRenderer.invoke("community:matches", forceRefresh) as Promise<CommunityMatch[]>,
  getHubMatches: (hubId, forceRefresh) => ipcRenderer.invoke("hubs:matches", hubId, forceRefresh) as Promise<CommunityMatch[]>,
  createHub: (name, password) => ipcRenderer.invoke("hubs:create", name, password) as Promise<HubActionResult>,
  joinHub: (name, password) => ipcRenderer.invoke("hubs:join", name, password) as Promise<HubActionResult>,
  syncPrivateHubs: () => ipcRenderer.invoke("hubs:sync-private") as Promise<PrivateHubSyncResult>,
  syncMatchesToHubs: (matchIds, hubIds) => ipcRenderer.invoke("hubs:sync-selected", matchIds, hubIds) as Promise<PrivateHubSyncResult>,
  deleteHubMatch: (hubId, matchId) => ipcRenderer.invoke("hubs:delete-match", hubId, matchId) as Promise<void>,
  startAccountLink: () => ipcRenderer.invoke("account:link:start") as ReturnType<RiftLiteApi["startAccountLink"]>,
  getAccountLinkStatus: (sessionId) => ipcRenderer.invoke("account:link:status", sessionId) as ReturnType<RiftLiteApi["getAccountLinkStatus"]>,
  getAccountProfile: () => ipcRenderer.invoke("account:profile:get") as ReturnType<RiftLiteApi["getAccountProfile"]>,
  saveAccountProfile: (profile) => ipcRenderer.invoke("account:profile:save", profile) as ReturnType<RiftLiteApi["saveAccountProfile"]>,
  refreshAccountProfileMatches: () => ipcRenderer.invoke("account:profile:backfill") as ReturnType<RiftLiteApi["refreshAccountProfileMatches"]>,
  exportAccountData: () => ipcRenderer.invoke("account:export") as ReturnType<RiftLiteApi["exportAccountData"]>,
  unlinkAccount: () => ipcRenderer.invoke("account:unlink") as ReturnType<RiftLiteApi["unlinkAccount"]>,
  searchPublicProfiles: (query) => ipcRenderer.invoke("profiles:search", query) as ReturnType<RiftLiteApi["searchPublicProfiles"]>,
  claimHub: (hubId, passwordHash) => ipcRenderer.invoke("hubs:claim", hubId, passwordHash) as ReturnType<RiftLiteApi["claimHub"]>,
  getHubInbox: () => ipcRenderer.invoke("hubs:inbox") as ReturnType<RiftLiteApi["getHubInbox"]>,
  acceptHubInvite: (inviteId) => ipcRenderer.invoke("hubs:invite:accept", inviteId) as ReturnType<RiftLiteApi["acceptHubInvite"]>,
  declineHubInvite: (inviteId) => ipcRenderer.invoke("hubs:invite:decline", inviteId) as ReturnType<RiftLiteApi["declineHubInvite"]>,
  getHubMembers: (hubId) => ipcRenderer.invoke("hubs:members", hubId) as ReturnType<RiftLiteApi["getHubMembers"]>,
  createHubInvite: (hubId, targetHandle) => ipcRenderer.invoke("hubs:invite", hubId, targetHandle) as ReturnType<RiftLiteApi["createHubInvite"]>,
  getHubMessages: (hubId) => ipcRenderer.invoke("hubs:messages", hubId) as ReturnType<RiftLiteApi["getHubMessages"]>,
  postHubMessage: (hubId, text) => ipcRenderer.invoke("hubs:message:post", hubId, text) as ReturnType<RiftLiteApi["postHubMessage"]>,
  deleteHubMessage: (hubId, messageId) => ipcRenderer.invoke("hubs:message:delete", hubId, messageId) as ReturnType<RiftLiteApi["deleteHubMessage"]>,
  getUpdateStatus: () => ipcRenderer.invoke("updates:status") as Promise<UpdateStatus>,
  checkForUpdates: () => ipcRenderer.invoke("updates:check") as Promise<UpdateStatus>,
  downloadUpdate: () => ipcRenderer.invoke("updates:download") as Promise<UpdateStatus>,
  installUpdate: () => ipcRenderer.invoke("updates:install") as Promise<void>,
  getGamePreloadUrl: (platform: GamePlatform) => ipcRenderer.invoke("game-preload:url", platform) as Promise<string>,
  getAssetUrl: (relativePath: string) => ipcRenderer.invoke("assets:url", relativePath) as Promise<string>,
  getBattlefields: () => ipcRenderer.invoke("battlefields:get") as Promise<BattlefieldOption[]>,
  notifyMatchReady: (draft) => ipcRenderer.invoke("notification:match-ready", draft) as Promise<void>,
  detectBrowsers: () => ipcRenderer.invoke("browsers:detect") as Promise<BrowserInfo[]>,
  getOverlayInfo: () => ipcRenderer.invoke("overlay:info") as Promise<OverlayInfo>,
  openOverlayTextFolder: () => ipcRenderer.invoke("overlay:open-text-folder") as Promise<void>,
  getDiagnosticsPath: () => ipcRenderer.invoke("diagnostics:path") as Promise<string>,
  getDiagnosticsSummary: () => ipcRenderer.invoke("diagnostics:summary") as Promise<CaptureDiagnosticsSummary>,
  createDiagnosticsBundle: () => ipcRenderer.invoke("diagnostics:bundle") as Promise<string>,
  openDiagnosticsFolder: () => ipcRenderer.invoke("diagnostics:open") as Promise<void>,
  takeScreenshot: () => ipcRenderer.invoke("screenshot:take") as Promise<ScreenshotResult>,
  chooseScreenshotDirectory: () => ipcRenderer.invoke("screenshot:choose-directory") as Promise<UserSettings>,
  openScreenshotDirectory: () => ipcRenderer.invoke("screenshot:open-directory") as Promise<void>,
  chooseReplayDirectory: () => ipcRenderer.invoke("replays:choose-directory") as Promise<UserSettings>,
  openReplayDirectory: () => ipcRenderer.invoke("replays:open-directory") as Promise<void>,
  openExternalResource: (url: string) => ipcRenderer.invoke("external:open", url) as Promise<void>,
  setWindowFullscreen: (enabled) => ipcRenderer.invoke("window:fullscreen", enabled) as Promise<boolean>,
  trackSpotlightClick: (payload) => ipcRenderer.invoke("analytics:spotlight-click", payload) as Promise<void>,
  reportRendererEvent: (event) => ipcRenderer.invoke("capture:renderer-event", event) as Promise<void>,
  onCaptureEvent: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: CaptureEvent) => callback(payload);
    ipcRenderer.on("capture:event", listener);
    return () => ipcRenderer.removeListener("capture:event", listener);
  },
  onCaptureHealth: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: CaptureHealth) => callback(payload);
    ipcRenderer.on("capture:health", listener);
    return () => ipcRenderer.removeListener("capture:health", listener);
  },
  onMatchDraft: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: MatchDraft) => callback(payload);
    ipcRenderer.on("match:draft", listener);
    return () => ipcRenderer.removeListener("match:draft", listener);
  },
  onScreenshotSaved: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: ScreenshotResult) => callback(payload);
    ipcRenderer.on("screenshot:saved", listener);
    return () => ipcRenderer.removeListener("screenshot:saved", listener);
  },
  onUpdateStatus: (callback) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: UpdateStatus) => callback(payload);
    ipcRenderer.on("updates:status", listener);
    return () => ipcRenderer.removeListener("updates:status", listener);
  }
};

contextBridge.exposeInMainWorld("riftlite", api);
